name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Execute when pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Changed from read to write
      pages: write
      id-token: write # Required when using OIDC tokens
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Adjust to the Node.js version used in the project
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/client # Directory specified in the deploy script of package.json
          # Optional: Commit user information
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'